name: res_env
channels:
  - defaults
dependencies:
  - bottleneck
  - ipykernel
  - numpy
  - seaborn
  - dask
  - netcdf4
  - py-xgboost
  - pandas
  - scikit-learn
  - python=3.11
  - pytorch::pytorch
  - xarray
  - feature_engine
