name: res_env
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - seaborn
  - scikit-learn
  - ipykernel
  - xarray
  - netcdf4
  - bottleneck
  - dask
  - py-xgboost
  - pytorch::pytorch
